// Yêu cầu cần đạt Địa lí 10 (CT GDPT 2018) theo mã AIDA – sinh tự động từ tệp mã hoá mục tiêu
export const OBJ = {
"DL10.00.01": "Khái quát được đặc điểm cơ bản của môn Địa lí.",
"DL10.00.02": "Xác định được vai trò của môn Địa lí đối với đời sống.",
"DL10.00.03": "Xác định được những ngành nghề có liên quan đến kiến thức địa lí.",
"DL10.01.01": "Phân biệt được một số phương pháp biểu hiện các đối tượng địa lí trên bản đồ: kí hiệu, đường chuyển động, chấm điểm, khoanh vùng, bản đồ – biểu đồ.",
"DL10.01.02": "Sử dụng được bản đồ trong học tập địa lí và đời sống.",
"DL10.01.03": "Xác định và sử dụng được một số ứng dụng của GPS và bản đồ số trong đời sống.",
"DL10.02.01": "Trình bày được nguồn gốc hình thành Trái Đất, đặc điểm của vỏ Trái Đất, các vật liệu cấu tạo vỏ Trái Đất.",
"DL10.02.02": "Phân tích được hệ quả địa lí của các chuyển động chính của Trái Đất: chuyển động tự quay (sự luân phiên ngày đêm, giờ trên Trái Đất); chuyển động quanh Mặt Trời (các mùa trong năm, ngày đêm dài ngắn theo vĩ độ).",
"DL10.02.03": "Liên hệ được thực tế địa phương về các mùa trong năm và chênh lệch thời gian ngày đêm.",
"DL10.02.04": "Sử dụng hình vẽ, lược đồ để phân tích được các hệ quả chuyển động của Trái Đất.",
"DL10.03.01": "Trình bày được khái niệm thạch quyển; phân biệt được thạch quyển với vỏ Trái Đất.",
"DL10.03.02": "Trình bày được khái quát thuyết kiến tạo mảng; vận dụng để giải thích được nguyên nhân hình thành các vùng núi trẻ, các vành đai động đất, núi lửa.",
"DL10.03.03": "Trình bày khái niệm nội lực, ngoại lực; nguyên nhân của chúng; tác động đến sự hình thành địa hình bề mặt Trái Đất.",
"DL10.03.04": "Phân tích được sơ đồ, lược đồ, tranh ảnh về tác động của nội lực, ngoại lực đến địa hình bề mặt Trái Đất.",
"DL10.03.05": "Nhận xét và giải thích được sự phân bố các vành đai động đất, núi lửa trên bản đồ.",
"DL10.04.01": "Nêu được khái niệm khí quyển.",
"DL10.04.02": "Trình bày được sự phân bố nhiệt độ không khí trên Trái Đất theo vĩ độ địa lí; lục địa, đại dương; địa hình.",
"DL10.04.03": "Trình bày được sự hình thành các đai khí áp trên Trái Đất, nguyên nhân của sự thay đổi khí áp.",
"DL10.04.04": "Trình bày được một số loại gió chính trên Trái Đất; một số loại gió địa phương.",
"DL10.04.05": "Phân tích được các nhân tố ảnh hưởng đến lượng mưa và trình bày được sự phân bố mưa trên thế giới.",
"DL10.04.06": "Phân tích được bảng số liệu, hình vẽ, bản đồ, lược đồ về một số yếu tố của khí quyển (nhiệt độ, khí áp, gió, mưa).",
"DL10.04.07": "Đọc được bản đồ các đới khí hậu trên Trái Đất; phân tích được biểu đồ một số kiểu khí hậu.",
"DL10.04.08": "Giải thích được một số hiện tượng thời tiết và khí hậu trong thực tế.",
"DL10.05.01": "Nêu được khái niệm thuỷ quyển.",
"DL10.05.02": "Phân tích được các nhân tố ảnh hưởng tới chế độ nước sông.",
"DL10.05.03": "Trình bày được chế độ nước của một con sông cụ thể.",
"DL10.05.04": "Phân biệt được các loại hồ theo nguồn gốc hình thành.",
"DL10.05.05": "Trình bày được đặc điểm chủ yếu của nước băng tuyết và nước ngầm.",
"DL10.05.06": "Nêu được các giải pháp bảo vệ nguồn nước ngọt.",
"DL10.05.07": "Trình bày được tính chất của nước biển và đại dương.",
"DL10.05.08": "Giải thích được hiện tượng sóng biển và thuỷ triều.",
"DL10.05.09": "Trình bày được chuyển động của các dòng biển trong đại dương.",
"DL10.05.10": "Nêu được vai trò của biển và đại dương đối với phát triển kinh tế – xã hội.",
"DL10.05.11": "Vẽ được sơ đồ; phân tích được bản đồ và hình vẽ về thuỷ quyển.",
"DL10.06.01": "Trình bày được khái niệm về đất; phân biệt được lớp vỏ phong hoá và đất.",
"DL10.06.02": "Trình bày được các nhân tố hình thành đất; liên hệ được thực tế ở địa phương.",
"DL10.06.03": "Trình bày được khái niệm sinh quyển; phân tích được đặc điểm và giới hạn của sinh quyển, các nhân tố ảnh hưởng đến sự phát triển, phân bố của sinh vật; liên hệ được thực tế ở địa phương.",
"DL10.06.04": "Phân tích được sơ đồ, hình vẽ, bản đồ phân bố các nhóm đất và sinh vật trên thế giới.",
"DL10.07.01": "Trình bày khái niệm vỏ địa lí; phân biệt được vỏ địa lí và vỏ Trái Đất.",
"DL10.07.02": "Trình bày được khái niệm, biểu hiện và ý nghĩa thực tiễn của quy luật thống nhất và hoàn chỉnh của vỏ địa lí; liên hệ được thực tế ở địa phương.",
"DL10.07.03": "Trình bày khái niệm, biểu hiện và ý nghĩa thực tiễn của quy luật địa đới và phi địa đới; liên hệ được thực tế ở địa phương.",
"DL10.07.04": "Giải thích được một số hiện tượng phổ biến trong môi trường tự nhiên bằng các quy luật địa lí.",
"DL10.08.01": "Trình bày được đặc điểm và tình hình phát triển dân số trên thế giới.",
"DL10.08.02": "Phân biệt được gia tăng dân số tự nhiên (tỉ suất sinh, tỉ suất tử) và cơ học (xuất cư, nhập cư), trình bày được khái niệm về gia tăng dân số thực tế; phân tích được các nhân tố tác động đến gia tăng dân số.",
"DL10.08.03": "Trình bày được các loại cơ cấu dân số: cơ cấu sinh học (tuổi và giới), cơ cấu xã hội (lao động, trình độ văn hoá).",
"DL10.08.04": "Phân tích được tác động của các nhân tố tự nhiên, kinh tế – xã hội đến phân bố dân cư.",
"DL10.08.05": "Trình bày được khái niệm, phân tích được các nhân tố tác động đến đô thị hoá và ảnh hưởng của đô thị hoá đến sự phát triển kinh tế – xã hội và môi trường.",
"DL10.08.06": "So sánh được các loại tháp dân số tiêu biểu.",
"DL10.08.07": "Vẽ được biểu đồ về dân số (quy mô, động thái, cơ cấu).",
"DL10.08.08": "Phân tích được biểu đồ, số liệu thống kê về dân số; xử lí số liệu.",
"DL10.08.09": "Nhận xét, giải thích được sự phân bố dân cư thông qua bản đồ, tài liệu, số liệu,...",
"DL10.08.10": "Giải thích được một số hiện tượng về dân số trong thực tiễn.",
"DL10.09.01": "Trình bày được khái niệm và phân loại các nguồn lực, phân tích được vai trò của mỗi loại nguồn lực đối với phát triển kinh tế.",
"DL10.09.02": "Trình bày được khái niệm cơ cấu kinh tế; phân biệt được các loại cơ cấu kinh tế theo ngành, theo thành phần kinh tế, theo lãnh thổ.",
"DL10.09.03": "So sánh được một số tiêu chí đánh giá sự phát triển kinh tế: tổng sản phẩm trong nước (GDP), tổng thu nhập quốc gia (GNI), GDP và GNI bình quân đầu người.",
"DL10.09.04": "Liên hệ được một số tiêu chí đánh giá sự phát triển kinh tế ở địa phương.",
"DL10.09.05": "Phân tích được sơ đồ nguồn lực và cơ cấu nền kinh tế.",
"DL10.09.06": "Vẽ được biểu đồ cơ cấu nền kinh tế và nhận xét, giải thích.",
"DL10.10.01": "Trình bày được vai trò, đặc điểm của nông nghiệp, lâm nghiệp, thuỷ sản.",
"DL10.10.02": "Phân tích được các nhân tố ảnh hưởng tới sự phát triển và phân bố nông nghiệp, lâm nghiệp, thuỷ sản; những định hướng phát triển nông nghiệp trong tương lai.",
"DL10.10.03": "Trình bày được vai trò, đặc điểm của các ngành trong nông nghiệp, lâm nghiệp, thuỷ sản.",
"DL10.10.04": "Trình bày và giải thích được sự phân bố của một số cây trồng, vật nuôi chính trên thế giới.",
"DL10.10.05": "Trình bày được quan niệm, vai trò của tổ chức lãnh thổ nông nghiệp; phân biệt được vai trò, đặc điểm một số hình thức tổ chức lãnh thổ nông nghiệp.",
"DL10.10.06": "Nêu được một số vấn đề phát triển nền nông nghiệp hiện đại trên thế giới.",
"DL10.10.07": "Vận dụng được các kiến thức đã học vào việc giải thích thực tế sản xuất nông nghiệp, lâm nghiệp, thuỷ sản ở địa phương.",
"DL10.10.08": "Đọc được bản đồ; xử lí, phân tích được số liệu thống kê và vẽ được biểu đồ về nông nghiệp, lâm nghiệp, thuỷ sản.",
"DL10.11.01": "Trình bày được vai trò, đặc điểm, cơ cấu ngành công nghiệp.",
"DL10.11.02": "Phân tích được các nhân tố ảnh hưởng tới sự phát triển và phân bố công nghiệp.",
"DL10.11.03": "Nêu được những định hướng phát triển công nghiệp trong tương lai.",
"DL10.11.04": "Trình bày được vai trò, đặc điểm và giải thích được sự phân bố của một số ngành: khai thác than, dầu khí, quặng kim loại; điện lực; điện tử, tin học; sản xuất hàng tiêu dùng; thực phẩm.",
"DL10.11.05": "Phân tích được tác động của công nghiệp đối với môi trường, sự cần thiết phải phát triển mạnh các nguồn năng lượng tái tạo.",
"DL10.11.06": "Trình bày được quan niệm, vai trò của tổ chức lãnh thổ công nghiệp; phân biệt được vai trò và đặc điểm của các hình thức tổ chức lãnh thổ công nghiệp.",
"DL10.11.07": "Thu thập tài liệu, trình bày và báo cáo được một vấn đề về công nghiệp.",
"DL10.11.08": "Đọc được bản đồ công nghiệp; vẽ và phân tích được biểu đồ về công nghiệp.",
"DL10.12.01": "Trình bày được cơ cấu, vai trò, đặc điểm của dịch vụ; phân tích được các nhân tố ảnh hưởng tới phát triển và phân bố dịch vụ.",
"DL10.12.02": "Trình bày được vai trò và đặc điểm của ngành giao thông vận tải, bưu chính viễn thông, thương mại, du lịch, tài chính ngân hàng.",
"DL10.12.03": "Phân tích được các nhân tố ảnh hưởng đến sự phát triển và phân bố của giao thông vận tải, bưu chính viễn thông, thương mại, du lịch, tài chính ngân hàng; trình bày được tình hình phát triển và phân bố các ngành này trên thế giới.",
"DL10.12.04": "Vẽ được biểu đồ, sơ đồ; đọc và phân tích được bản đồ, số liệu thống kê ngành dịch vụ.",
"DL10.12.05": "Liên hệ được các hoạt động dịch vụ tại địa phương.",
"DL10.12.06": "Viết được báo cáo tìm hiểu về một ngành dịch vụ.",
"DL10.13.01": "Phân biệt được khái niệm, đặc điểm của môi trường và tài nguyên thiên nhiên.",
"DL10.13.02": "Phân tích được vai trò của môi trường, tài nguyên thiên nhiên đối với sự phát triển của xã hội loài người.",
"DL10.13.03": "Trình bày được khái niệm và sự cần thiết phải phát triển bền vững.",
"DL10.13.04": "Trình bày được khái niệm và biểu hiện của tăng trưởng xanh.",
"DL10.13.05": "Liên hệ được một số vấn đề về tăng trưởng xanh tại địa phương.",
"DL10.CD1.01": "Trình bày được khái niệm, các biểu hiện của biến đổi khí hậu.",
"DL10.CD1.02": "Giải thích được nguyên nhân của biến đổi khí hậu.",
"DL10.CD1.03": "Phân tích được các tác động của biến đổi khí hậu và hậu quả trên phạm vi toàn cầu.",
"DL10.CD1.04": "Giải thích được tầm quan trọng và sự cấp bách của ứng phó với biến đổi khí hậu.",
"DL10.CD1.05": "Hệ thống hoá được các nhóm giải pháp ứng phó với biến đổi khí hậu.",
"DL10.CD2.01": "Trình bày được khái niệm về đô thị hoá theo nghĩa hẹp và nghĩa rộng.",
"DL10.CD2.02": "Nêu được ý nghĩa của tỉ lệ dân thành thị.",
"DL10.CD2.03": "Phân tích được đặc điểm đô thị hoá ở các nước phát triển.",
"DL10.CD2.04": "Phân biệt được quy mô của các đô thị.",
"DL10.CD2.05": "Nhận xét và giải thích được xu hướng đô thị hoá ở các nước phát triển.",
"DL10.CD2.06": "Phân tích được đặc điểm đô thị hoá ở các nước đang phát triển.",
"DL10.CD2.07": "Nhận xét và giải thích được xu hướng đô thị hoá ở các nước đang phát triển.",
"DL10.CD2.08": "So sánh được đặc điểm đô thị hoá giữa hai nhóm nước: phát triển, đang phát triển.",
"DL10.CD2.09": "Phân tích được tác động tích cực và tiêu cực của quá trình đô thị hoá đến dân số, kinh tế, xã hội và môi trường ở các nước đang phát triển.",
"DL10.CD2.10": "Liên hệ được với thực tế Việt Nam.",
"DL10.CD2.11": "Vẽ được biểu đồ cơ cấu dân số phân theo thành thị và nông thôn của thế giới hoặc một số nước.",
"DL10.CD2.12": "Xác định được trên bản đồ, lược đồ thế giới một số siêu đô thị.",
"DL10.CD3.01": "Nêu được quan niệm về báo cáo địa lí.",
"DL10.CD3.02": "Trình bày được cấu trúc của một báo cáo địa lí.",
"DL10.CD3.03": "Xác định được các bước cần thực hiện để viết một báo cáo địa lí: chọn đề tài, xây dựng đề cương; thu thập, chọn lọc, xử lí và hệ thống hoá tư liệu; trình bày báo cáo.",
"DL10.CD3.04": "Xác định được ý tưởng và chọn đề tài báo cáo địa lí.",
"DL10.CD3.05": "Xác định được cấu trúc của một đề cương báo cáo khoa học địa lí và nội dung chính của các đề mục.",
"DL10.CD3.06": "Xác định và hình thành được kĩ năng thu thập, chọn lọc, xử lí thông tin, hệ thống hoá thông tin.",
"DL10.CD3.07": "Xác định được cách thức trình bày báo cáo.",
"DL10.CD3.08": "Trình bày được kĩ thuật viết một báo cáo địa lí; hình thành được kĩ năng viết và trình bày báo cáo địa lí."
};
export const CHAP = {"00": "Mở đầu – Môn Địa lí với định hướng nghề nghiệp", "01": "Sử dụng bản đồ", "02": "Trái Đất", "03": "Thạch quyển", "04": "Khí quyển", "05": "Thuỷ quyển", "06": "Sinh quyển", "07": "Một số quy luật của vỏ địa lí", "08": "Địa lí dân cư", "09": "Các nguồn lực, một số tiêu chí đánh giá sự phát triển kinh tế", "10": "Địa lí ngành nông nghiệp, lâm nghiệp, thuỷ sản", "11": "Địa lí ngành công nghiệp", "12": "Địa lí ngành dịch vụ", "13": "Phát triển bền vững và tăng trưởng xanh", "CD1": "Chuyên đề 10.1: Biến đổi khí hậu", "CD2": "Chuyên đề 10.2: Đô thị hoá", "CD3": "Chuyên đề 10.3: Phương pháp viết báo cáo địa lí"};
